

describe("URL Redirects", function(){

  it('CMS', function() {cy.visit('webcms.kcl.ac.uk') })
  it('KCEP 1', function() {cy.visit('www.kcep.co.uk')})
  it('KCEP 2', function() {cy.visit('kcep.co.uk')})
  it('Shakespeare 1', function() {cy.visit('www.shakespeare.kcl.ac.uk')})
  it('Shakespeare 2', function() {cy.visit('shakespeare.kcl.ac.uk')})
  it('Reading List', function() {cy.visit('readinglist.kcl.ac.uk')})
  it('Pharm 1', function() {cy.visit('www.pharm-med.kcl.ac.uk')})
  it('Pharm 2', function() {cy.visit('pharm-med.kcl.ac.uk')})
  it('Service Desk', function() {cy.visit('servicedesk.kcl.ac.uk')})
  it('Service Desk 8888', function() {cy.visit('8888.kcl.ac.uk')})
  it('Service Desk 88888', function() {cy.visit('88888.kcl.ac.uk')})
  it('Kinetics', function() {cy.visit('kineticsweb.adminsystems.adm.kcl.ac.uk')})
  it('Web Catering', function() {cy.visit('www.testwebcatering.kcl.ac.uk')})
  it('Test Webbnb', function() {cy.visit('www.testwebbnb.kcl.ac.uk')})
  it('Support', function() {cy.visit('www.support.kcl.ac.uk')})
  it('IT', function() {cy.visit('it.kcl.ac.uk')})
  it('IT Grads', function() {cy.visit('itgrads.kcl.ac.uk')})
  it('Kings Venue', function() {cy.visit('kingsvenues.com')})
  it('KCL PWord', function() {cy.visit('kclpword.kcl.ac.uk')})
  it('Password Reset', function() {cy.visit('passwordreset.kcl.ac.uk')})
  it('Password Reset Reg', function() {cy.visit('passwordregistration.kcl.ac.uk')})
  it('Office 365', function() {cy.visit('office365.kcl.ac.uk')})
  it('Finance', function() {cy.visit('finance.kcl.ac.uk')})
  it('OCRU 1', function() {cy.visit('ocru.kcl.ac.uk')})
  it('OCRU 2', function() {cy.visit('www.ocru.kcl.ac.uk')})
  it('Atlas', function() {cy.visit('atlasofseas.kcl.ac.uk')})
  it('Worktribe', function() {cy.visit('worktribe.kcl.ac.uk')})
  it('Worktribe Train', function() {cy.visit('worktribe-train.kcl.ac.uk')})
  it('Worktribe Test', function() {cy.visit('worktribe-test.kcl.ac.uk')})
  it('GIWL', function() {cy.visit('giwl.kcl.ac.uk')})
  it('KEATS', function() {cy.visit('login-keats.kcl.ac.uk')})
  it('Spotlight', function() {cy.visit('spotlight.kcl.ac.uk')})
  it('MFA', function() {cy.visit('mfasetup.kcl.ac.uk')})
  it('Fed Serv Update Password', function() {cy.visit('fedserv.kcl.ac.uk/adfs/portal/updatepassword')})
  it('Fed Serv', function() {cy.visit('fedserv.kcl.ac.uk')})
  it('AISEP 2', function() {cy.visit('aisep.kcl.ac.uk')})
  
})